/*
 * Always On Mobile - hullo API
 * Welcome to the hullo API.    With this API you can perform operations on your hullo account programmatically that you can call using the hullo console. The operations currently available include:    * Add / Update a member * Get the details of a member * Get the messages sent / received from a member * Send a message to a member  The hullo API is an easy to use RESTful API that can be called by any modern programming language that  supports HTTP calls, and also has out of the box support for several programming languages including:   * Java * Javascript    In order to use the API you will first need to generate an API key using the hullo console application, assigning it the the relevant scopes required for the operations you wish to call. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.alwaysonmobile.hullo.api.client;

import io.alwaysonmobile.hullo.api.ApiException;
import io.alwaysonmobile.hullo.api.client.GenericError;
import io.alwaysonmobile.hullo.api.client.Member;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MembersApi
 */
@Ignore
public class MembersApiTest {

    private final MembersApi api = new MembersApi();

    /**
     * Gets the details for a member
     *
     * Retrieves the details hullo stores about a specific member. The record will contain any attribute data added  using either the hullo API or the hullo application along with the members phone number and full name. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMemberTest() throws ApiException {
        String phoneNumber = null;
        Member response = api.getMember(phoneNumber);

        // TODO: test validations
    }
    /**
     * Opts the member out from the hullo member store
     *
     * Opts out the member from the hullo member store which results in their record being deleted. Any pending  messages will also be deleted for the member and the member will no longer be able to participate in \\ any  campaigns. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void optOutMemberTest() throws ApiException {
        String phoneNumber = null;
        api.optOutMember(phoneNumber);

        // TODO: test validations
    }
    /**
     * Adds or updates a member
     *
     * Add or update the information hullo stores for a specific member. If the member doesn&#39;t already exist then    they will be added to the members store and an opt-in message will be sent to the number specified in order   to get confirmation that the number exists and wishes to receive messages. If the member responds with a   confirmation message (\&quot;yes\&quot;) then their member record will be updated to opted-in and they will then be able   to receive messages sent to them from any hullo campaign. If the member already exists then their record will  be updated to reflect any new / updated attribute data included in the call. If an attribute is specified but   no value is given or the value is null then that attribute will be deleted from the members record. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void upsertMemberTest() throws ApiException {
        Member member = null;
        Member response = api.upsertMember(member);

        // TODO: test validations
    }
}
